<body>
<script src="js/jquery.dataTables.js"></script>
<link href="css/jquery.dataTables_themeroller.css" rel="stylesheet" type="text/css">
<script language="Javascript" type="text/javascript" src="js/jquery.lwtCountdown-1.0.js"></script>
<link href="css/maincountdown.css" rel="stylesheet" type="text/css">

<?php $num=5;?>
<script type="text/javascript">
// Initiate Countdown
jQuery(document).ready(function() {
	$('#countdown_dashboard').countDown({
		targetOffset: {
			'day': 		0,
			'month': 	0,
			'year': 	0,
			'hour': 	0,
			'min': 		0,
			'sec': 		0
		}
	});
	
	$('#countdown_dashboard').setCountDown({
		targetDate: {
			'day': 		<?php echo date('j', $dueOn); ?>,
			'month': 	<?php echo date('n', $dueOn); ?>,
			'year': 	<?php echo date('Y', $dueOn); ?>,
			'hour': 	<?php echo date('G', $dueOn); ?>,
			'min': 		<?php echo date('i', $dueOn); ?>,
			'sec': 		<?php echo date('s', $dueOn); ?>
		}
	});
	$('#countdown_dashboard').startCountDown();
});
</script>

</body>

<li name="boxed">
<h3>
    <?php echo Utils::escape($todo->getTitle()); ?>
</h3>

<table class="detail"> 
    <tr>
        <th>Priority:</th>
        <td><img src="img/priority/<?php echo $todo->getPriority(); ?>.png" alt="Priority <?php echo $todo->getPriority(); ?>" title="Priority <?php echo $todo->getPriority(); ?>" /></td>
        
    </tr>
    <tr>
        <th>Created On:</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getCreatedOn())); ?></td>
    </tr>
    <tr>
        <th>Due On:</th>
        <td>
            <?php if ($tooLate): ?><span class="too-late"><?php endif; ?>
            <?php
		$dueOn = $todo->getDueOn();
		echo Utils::escape(Utils::formatDateTime($todo->getDueOn())); ?>
            <?php if ($tooLate): ?></span><?php endif; ?>
            <?php if ($tooLate): ?>
        <img src="img/exclamation.png" alt="" title="This project is past deadline!" />
    <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th>Last Modified:</th>    
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getLastModifiedOn())); ?></td>
    </tr>
    <tr>
	<th>Assigned To:</th>
	<td><?php

		$db = $dao->getDb();
		$tempId = $todo->getId();
		$query = "SELECT name FROM worksOn, employee WHERE pid = '$tempId' AND eid = id";
		$result = $db->query($query) or die("error showing details");
	       while($row = $result->fetch(PDO::FETCH_ASSOC)) {
			?><employee><?php echo $row['name']; ?></employee></br><?php
		} 
		$dao->__destruct;  ?></td>
    </tr>
    <tr>
        <th>Description:</th>
        <td><?php echo Utils::escape($todo->getDescription()); ?></td>
    </tr>
    <tr>
        <th>Comment:</th>
        <td><?php echo Utils::escape($todo->getComment()); ?></td>
    </tr>
    <tr>
        <th>Status:</th>
        <td><img src="img/status/<?php echo $todo->getStatus(); ?>.png" alt="" title="<?php echo Utils::capitalize($todo->getStatus()); ?>" class="icon" /></td>
    </tr>
    <tr>
        <!--<div id="countdown_dashboard">
			<div class="dash weeks_dash">
				<span class="dash_title">weeks</span>
				<div class="digit"><?=$date['weeks'][0]?></div>
				<div class="digit"><?=$date['weeks'][1]?></div>
			</div>

			<div class="dash days_dash">
				<span class="dash_title">days</span>
				<div class="digit"><?=$date['days'][0]?></div>
				<div class="digit"><?=$date['days'][1]?></div>
			</div>

			<div class="dash hours_dash">
				<span class="dash_title">hours</span>
				<div class="digit"><?=$date['hours'][0]?></div>
				<div class="digit"><?=$date['hours'][1]?></div>
			</div>

			<div class="dash minutes_dash">
				<span class="dash_title">minutes</span>
				<div class="digit"><?=$date['mins'][0]?></div>
				<div class="digit"><?=$date['mins'][1]?></div>
			</div>

			<div class="dash seconds_dash">
				<span class="dash_title">seconds</span>
				<div class="digit"><?=$date['secs'][0]?></div>
				<div class="digit"><?=$date['secs'][1]?></div>
			</div>

		</div> -->
    </tr>
    <tr>
        <th><?php if(isset($_SESSION['name'])) { ?>Actions:<?php } ?></th>
        <td>
            <?php
                if(isset($_SESSION['name'])) {
            ?>
            	    <div class="statuses">
            		<?php foreach (Todo::allStatuses() as $status): ?>
                		<?php if ($status != $todo->getStatus()): ?>
                    			<a href="<?php echo Utils::createLink('change-status', array('id' => $todo->getId(), 'status' => $status)); ?>" title="Change project status to <?php echo Utils::capitalize($status); ?>." class="change-status-link">
					<img src="img/status/<?php echo $status; ?>.png" alt="" title="Make it <?php echo Utils::capitalize($status); ?>." class="icon" /></a>
                		<?php else: ?>
                    			<img src="img/status/<?php echo $status; ?>-disabled.png" alt="" title="This project is already <?php echo Utils::capitalize($status); ?>." class="icon" />
                		<?php endif; ?>
            		<?php endforeach; ?>
                	<a href="<?php echo Utils::createLink('add-edit', array('id' => $todo->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                	<a href="<?php echo Utils::createLink('delete', array('id' => $todo->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            	    </div>
            <?php
                }
            ?>
	
        </td>
    </tr> 
</table>
	<?php
	$db = $dao->getDb();
	$tempId = $todo->getId();

	$query = "SELECT * FROM task WHERE pid = '$tempId'";
	$result = $db->query($query) or die("error showing details");
	?>
   
    <table id="dataTable"> 
	<thead>
       	 <tr>
        		<th>Milestone</th>
        		<th>Employee</th>
			<th>Start</th>
			<th>Finish</th>
			<th>Duration (days)</th>
			<th>Finished On</th>
			<?php if (isset($_SESSION['name'])) { ?>
				<th>Actions</th>
			<?php } ?>
    		</tr>

	</thead>
	<tbody>

	 <?php
		while($row = $result->fetch(PDO::FETCH_ASSOC)) {
			$start = $row['start'];
			$end = $row['end'];

			$startDate = strtotime($start);
			$endDate = strtotime($end);
			$interval = floor(($endDate - $startDate)/86400);
			$title = $row['title'];
			$tid = $row['tid'];
			$completed = $row['completedOn'];
			$completedDate = strtotime($completed);

			$today = time();
			$timeInterval = floor(($today - $endDate)/86400);
			if ($completed) {
				$compInterval = floor(($completedDate - $endDate)/86400);
			}

			$query2 = "SELECT eid FROM onTask WHERE tid = '$tid'";
			$result2 = $db->query($query2) or die("Employee milestone query failed.");
			while($row2 = $result2->fetch(PDO::FETCH_ASSOC)) {
				$eid = $row2['eid'];
				$query3 = "SELECT name FROM employee WHERE id = '$eid'";
				$result3 = $db->query($query3) or die("Employee name query failed.");
				$row3 = $result3->fetch(PDO::FETCH_ASSOC);
				$ename = $row3['name'];
	?>
		<tr style="<?php if ($completed && ($compInterval > 0)) { echo 'color:#D67D1E'; }
			          elseif ($completed) { echo 'color:green'; }
				   elseif ($timeInterval > 0) { echo 'color:#FF0000'; } ?>">
			<th><?php echo $title; ?></th>
			<th><?php echo $ename; ?></th>
			<th><?php echo date('F d, Y', strtotime($start)); ?></th>
			<th><?php echo date('F d, Y', strtotime($end)); ?></th>
			<th><?php echo $interval; ?></th>
			<th><?php if ($completed) { echo date('F d, Y', $completedDate); }?></th>
			<?php if (isset($_SESSION['name'])) { ?>
			<th>
				<a href="<?php if ($completed) { echo Utils::createLink('open-ms'); } 
					   else { echo Utils::createLink('complete-ms'); } ?>&tid=<?php echo $tid; ?>" 
					class="<?php if ($completed) { echo 'open-ms-link'; }
							else { echo 'complete-milestone-link'; } ?>">
					<img src="<?php if ($completed) { echo 'img/status/CURRENT.png'; } 
							else { echo 'img/status/COMPLETED.png'; } ?>" alt="" 
					title="<?php if ($completed) { echo 'Re-open milestone.'; } 
							else { echo 'Complete milestone.'; } ?>" class="icon" style="width:18px; height: 18px; margin: 0;"/></a>&nbsp;

				<a href="<?php echo Utils::createLink('add-milestone'); ?>&tid=<?php echo $tid; ?>"><img src="img/action/edit.png" alt="" title="Edit milestone." class="icon" style="width:18px; height: 18px; margin:0;"/></a>&nbsp;
				<a href="<?php echo Utils::createLink('delete-ms'); ?>&tid=<?php echo $tid; ?>" class="delete-ms"><img src="img/status/CANCELED.png" alt="" title="Delete milestone." class="icon" style="width:18px; height: 18px; margin:0;"/></a>
			</th>
			<?php } ?>
		</tr>
	<?php 	}	} ?>
	</tbody>
    </table>


    <?php
	if(isset($_SESSION['name'])) {
    ?>
    	 </br>
    	 <a href="<?php echo Utils::createLink('add-milestone'); ?>"><img src="img/action/add.png" alt="" title="Add Milestone." class="icon"/>Add Milestone.</a>
 
    <?php 
	} 
    ?>
</li>

<p>
    <?php $backLink = Utils::createLink('list', array('status' => $todo->getStatus())); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this project?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This project will be deleted. Are you sure?</p>
</div>
<div id="delete-ms-dialog" title="Delete this milestone?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This milestone will be deleted. Are you sure?</p>
</div>
<div id="open-ms-dialog" title="Re-open this milestone?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This milestone will be re-opened. Are you sure?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
<div id="complete-milestone-dialog">
    <form id="complete-milestone-form" method="post">
        <fieldset>
            <div class="field">
                <label>Finished On:</label>
                <input type="text" name="dp" class="datepicker" />
            </div>
        </fieldset>
    </form>
</div>

