<?php

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of TODOs to be displayed
//  $todos - TODOs to be displayed

?>

<p>
	<h1><?php echo $title; ?></h1>
</p>

<?php if (empty($todos)): ?>
    <p>No projects found.</p>
<?php else: ?>

    <ul class="list">
        <?php foreach ($todos as $todo): ?>   
            <?php 			
			$filter = false;
			if(isset($_SESSION['filtering'][0])) {
				$array = explode(',', $_SESSION['filtering']);
				$tempId = $todo->getId();
			    $dao = new TodoDao();
                            $db = $dao->getDb();
				$sql = "SELECT eid FROM worksOn WHERE pid = '$tempId'";
				$result = $db->query($sql) or die("error showing details");
				while($row = $result->fetch(PDO::FETCH_ASSOC)) {
					
					for($i = 0; $i < count($array); $i++) { 
						if($row['eid'] == $array[$i]) { 
							$filter = true;
							break;	
						} 
					} 
					if($filter) {
						break;
					}
				}
                            $dao->__destruct();
			} 
			else {
				$filter = true;
			} 
		
		if($filter) { 
	     ?>
            <?php $tooLate = $status == Todo::STATUS_CURRENT && $todo->getDueOn() < new DateTime(); ?>
            <li name="boxed">
                    
                <h3><a href="<?php echo Utils::createLink('detail', array('id' => $todo->getId())) ?>"><?php echo Utils::escape($todo->getTitle()); ?>
                    <img src="img/priority/<?php echo $todo->getPriority(); ?>.png" alt="Priority <?php echo $todo->getPriority(); ?>" title="Priority <?php echo $todo->getPriority(); ?>" /></a>
                </h3>
                    
			
                <?php if ($todo->getDescription()): ?>
                    <p class="description"><?php echo Utils::escape($todo->getDescription()); ?></p>
                <?php endif; ?>
                <p><span class="label">Due On:</span>
                    <?php if ($tooLate): ?><span class="too-late"><?php endif; ?>
                    <?php echo Utils::escape(Utils::formatDateTime($todo->getDueOn())); ?>
                    <?php if ($tooLate): ?></span><?php endif; ?>
                    <?php if ($tooLate): ?>
                    <img src="img/exclamation.png" alt="" title="This project is past deadline!" />
                    <?php endif; ?>
                </p>
		

		<p><span class="label">Assigned to:<table>
		<?php
                     $db = $dao->getDb();
			$tempId = $todo->getId();
			$query = "SELECT name FROM worksOn, employee WHERE pid = '$tempId' AND eid = id";
			$result = $db->query($query) or die("error showing details");

	       	while($row = $result->fetch(PDO::FETCH_ASSOC)) {
			?><tr><td><employee><?php
				echo '- '.$row['name']; ?></employee></td></tr><?php
			}
                     $dao->__destruct();
		?>
		</span>
		</table>

	
            </li>
        <?php 
	}
	endforeach; ?>
    </ul>
<?php endif; ?>
